[package]
name = "sebi-core"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
wasmparser.workspace = true
sha2.workspace = true
hex.workspace = true

[dev-dependencies]
wat = "1"
